Feature/janitor monkey
mlafeldt/docker-simianarmy pull request #1
Opened 2016-12-06 07:25 UTC by temyers

Add support for running JanitorMonkey

Also added the utility that I used to convert the default properties file from https://github.com/Netflix/SimianArmy/blob/master/src/main/resources/janitor.properties
It could be re-used for migrating other properties files (as a one-off activity).

2016-12-06 08:56 UTC, mlafeldt reviewed
Thanks for the PR!

Generally, I think that we should strip all those comments and document the keys in `docs/`. Otherwise, the generated config doesn't make much sense.

2016-12-06 08:56 UTC, mlafeldt commented on confd/templates/janitor.properties.tmpl
> +simianarmy.scheduler.frequency = {{getv "/simianarmy/scheduler/frequency" "1"}}
This is actually one of the problems I have with the key-value scheme: one `/simianarmy/scheduler` here again would mean that both Chaos and Janitor Monkey always do things at the same time.

2016-12-06 08:56 UTC, mlafeldt commented on confd/templates/janitor.properties.tmpl
> +simianarmy.janitor.enabled = {{getv "/simianarmy/janitor/enabled" "true"}}
This enables Janitor Monkey by default, which would change the current default behavior.

2016-12-06 08:56 UTC, mlafeldt commented on confd/templates/janitor.properties.tmpl
> +#simianarmy.calendar.isMonkeyTime = true
This comment looks obsolete.

2016-12-06 08:56 UTC, mlafeldt commented on confd/templates/janitor.properties.tmpl
> +#simianarmy.janitor.snapshots.ownerId = 012345678
Also superfluous, I guess.

2016-12-06 08:56 UTC, mlafeldt commented on update_properties.rb
> +## This utility makes it easy to convert the properties from the default properties file to use confd properties
Nice one-off script! But I don't think that we should add it to the repo.

2016-12-07 02:52 UTC, temyers commented on update_properties.rb
> +## This utility makes it easy to convert the properties from the default properties file to use confd properties
Ok, I'll remove.  

I've placed it here instead: https://gist.github.com/temyers/795f3f89ac94e8be85b4f9e1c6f298c0

2016-12-07 02:53 UTC, temyers commented on confd/templates/janitor.properties.tmpl
> +#simianarmy.janitor.snapshots.ownerId = 012345678
Yeah some of these comments were mainly so I could check that my script was working as expected - I'll remove

2016-12-07 02:54 UTC, temyers commented on confd/templates/janitor.properties.tmpl
> +simianarmy.janitor.enabled = {{getv "/simianarmy/janitor/enabled" "true"}}
I'll revert to false.

But in general, I think it should use the defaults from [SimianArmy](https://github.com/Netflix/SimianArmy) for consistency

2016-12-07 02:56 UTC, temyers commented on confd/templates/janitor.properties.tmpl
> +simianarmy.scheduler.frequency = {{getv "/simianarmy/scheduler/frequency" "1"}}
I don't really see that as a problem myself.  It is the way they are configured in the source and simplifies the configuration.

I can remove those properties, so they are configured in one place only.

2016-12-07 02:57 UTC, temyers commented
I shall update the docs and refer to the Netflix wiki for actual configuration options.

2017-07-04 11:23 UTC, mlafeldt requested changes
LGTM in general. Just a few minor things.

2017-07-04 11:23 UTC, mlafeldt commented on .gitignore
> +.project
What is this?

2017-07-04 11:23 UTC, mlafeldt commented on docs/configuration-properties.md
> +| simianarmy/janitor/enabled | true
This is not "true".

Also, could you please add a trailing "|" in every row for consistency?

2017-07-05 02:33 UTC, temyers commented on .gitignore
> +.project
.project are Eclipse project files.
Ignored, since the IDE is a preference of the developer, not the project.

2017-07-05 02:38 UTC, temyers commented on docs/configuration-properties.md
> +| simianarmy/janitor/enabled | true
👍

2017-07-05 05:01 UTC, mlafeldt approved these changes
LGTM. Thank you!

2017-07-05 05:01 UTC, merged